### ISSUE TITLE
Choose CMS Options

### ISSUE THREAD

**Issue by josiah14** [team-418/main-website#1]
We need to choose a CMS.  We should have a paid one and a free one as backup if the non-profit doesn't want to take on the risk of a paid service.

**Comment by josiah14** [comment]
My current research picks are 

[Scrivito](https://scrivito.com/), 
[Alchemy](https://www.alchemy-cms.com/about), 
[Radiant](http://radiantcms.org/), 
and [Refinery](http://www.refinerycms.com/).

**Comment by josiah14** [comment]
Research order:
1. Scrivito
2. Refinery
3. Alchemy
4. Radiant

**Comment by josiah14** [comment]
Each CMS trial should go into its own branch.  So if we research all 4 CMSes, then we should have 4 new branches - one for each.

Let me know if you need me to set-up another Heroku app(s) to deploy the CMS trials independently from the develop and master branches.

**Comment by josiah14** [comment]
@jj3 It looks like you've picked-up looking into Scrivito.  I'm going to open a branch for Alchemy and start working on that.

**Comment by jj3** [comment]
@josiah14 I started working on integrating Alchemy but ran into some errors while running their installation steps. We might want to skip this one for now and look into the other two. 

Scrivito's installation process was easy to follow and they have a lot of documentation. Given the short time we have until the hackathon and it seems really polished being a commercial product, we may want to focus on becoming proficient with it.

**Comment by josiah14** [comment]
@jj3 Agreed.  I'll work on learning more about Scrivito tomorrow evening - see how far I get.
