### ISSUE TITLE
Troubleshoot Stephanie's Docker setup

### ISSUE THREAD

**Issue by josiah14** [team-418/main-website#2]

**Comment by josiah14** [comment]
Stephanie seems to be having two issues:

- Write permissions to the mounted pgdata directory for Postgresql
- Port forwarding from the Docker container to the host machine to make the web app accessible from the host's web browsers.

There is a workaround for the permissions issues to just not create a local pgdata mount.  What this means is that Stephanie will need to make sure she commits her container anytime the database schema or data changes, or else she will lose all of her local changes.

The Port forwarding issue is more serious.  If this doesn't get fixed, she won't be able to run the container to access the website on the host.

**Comment by josiah14** [comment]
@JakeLaCombe @toddwalden @trogdor69 @appym @SudhakarReddyPeddinti 

I think you guys are also on OSX.  Maybe one of you could walk @stephaniehspicer through the steps you went through to install Docker for Mac and then run the container and see if we can identify what Stephanie did differently?

**Comment by SudhakarReddyPeddinti** [comment]
Sure. I will try to help with what i know.

**Comment by stephspicer** [comment]
It's working! I uninstalled docker toolbox and installed docker and it mostly went smoothly from there.

**Comment by stephspicer** [comment]
Thanks for your help Sudhakar and Josiah.

**Comment by josiah14** [comment]
@stephaniehspicer welcome!  glad it's working!  Docker rules!!!
